Editor/config/routes.rb
Heroes::Application.routes.draw do

  root 'pages#index'
  
  resources :fields
  resources :grounds
  resources :heroes
  resources :maps do
    get 'fields',    on: :member
    get 'randomize', on: :member
  end
  resources :mines
  resources :towns  
  resources :troops
  resources :troop_types
    
end

Editor/app/models/troop.rb
class Troop < ActiveRecord::Base
  belongs_to :town
  belongs_to :type, class_name: 'TroopType', foreign_key: :troop_type_id

  scope :by_name, -> { order( name: :asc ) }

  validates :abilities,  presence: true
  validates :cost,       presence: true
  validates :level,      presence: true
  validates :max_health, presence: true
  validates :max_damage, presence: true
  validates :min_damage, presence: true
  validates :name,       presence: true
  validates :range,      presence: true
  validates :town,       presence: true
  validates :type,       presence: true

  def as_json options = {}
    {
      id:            id,
      name:          name,
      cost:          cost.to_s,
      abilities:     abilities.to_s,
      level:         level.to_s,
      max_health:    max_health.to_s,
      max_damage:    max_damage.to_s,
      min_damage:    min_damage.to_s,
      range:         range.to_s,    
      upgrade:       upgrade.to_s, 
      town_id:       town_id,
      troop_type_id: troop_type_id
    }
  end  
end

Editor/app/models/troop_type.rb
class TroopType < ActiveRecord::Base
  has_many :troops

  scope :by_name, -> { order( name: :asc ) }

  validates :name, presence: true
  
  def as_json options = {}
    {
      id:       id,
      name:     name,
      shooting: shooting.to_s,
      magic:    magic.to_s,
      flying:   flying.to_s
    }
  end  
end

Editor/app/controllers/troops_controller.rb
# encoding: utf-8

class TroopsController < ApplicationController
  before_filter :get_troop, except: [:index, :new, :create]
  before_filter :get_towns, only: [:edit, :new, :create]

  def index
    @troops = Troop.includes( :town ).by_name

    respond_to do |format|
      format.html 
      format.json { send_data @troops.to_json, type: :json, disposition: 'attachment' }
    end      
  end

  def new
    @troop = Troop.new
  end

  def create
    @troop = Troop.create( troop_params )
    
    if @troop.save
      redirect_to troops_path, notice: 'Jednostka została dodana'
    else
      render 'new'
    end
  end

  def edit
  
  end

  def update
    @troop.update( troop_params )
    
    redirect_to troops_path, notice: 'Jednostka została zaktualizowana'
  end

  def destroy  
    @troop.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def get_towns
    @towns = Town.by_name
  end

  def get_troop
    @troop = Troop.find( params[:id] )
  end

  def troop_params
    params.require( :troop ).permit( 
      [:abilities, :cost, :level, :max_health, :max_damage, :min_damage, :name, :range, :town_id, :troop_type_id, :upgrade ] 
    )
  end  

end

Editor/app/helpers/troops_helper.rb
module TroopsHelper
end

Editor/app/views/troops/_errors.html.haml
- if @troop.errors.any?
  .alert.alert-danger
    %ul
      - @troop.errors.full_messages.each do |message|
        %li
          = message

Editor/app/views/troops/_form.html.haml
= form_for @troop do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label  :town_id
    = f.select :town_id, Town.by_name.collect{ |t| [t.name, t.id] }, { prompt: 'Wybierz miasto' }, class: 'form-control'
  .form-group
    = f.label  :troop_type_id
    = f.select :troop_type_id, TroopType.by_name.collect{ |t| [t.name, t.id] }, { prompt: 'Wybierz typ jednostki' }, class: 'form-control'    
  .form-group
    = f.label :cost
    = f.number_field :cost, class: 'form-control'    
  .form-group
    = f.label :level
    = f.number_field :level, class: 'form-control'    
  .form-group
    = f.label :upgrade
    = f.check_box :upgrade, class: 'form-control'        
  .form-group
    = f.label :abilities
    = f.number_field :abilities, class: 'form-control'
  .form-group
    = f.label :max_health
    = f.number_field :max_health, class: 'form-control'
  .form-group
    = f.label :max_damage
    = f.number_field :max_damage, class: 'form-control'
  .form-group
    = f.label :min_damage
    = f.number_field :min_damage, class: 'form-control'
  .form-group
    = f.label :range
    = f.number_field :range, class: 'form-control'
    
  = f.submit 'Zapisz', class: 'btn btn-default'

Editor/app/views/troops/destroy.js.erb
$( '#<%= dom_id( @troop ) %>' ).remove();

Editor/app/views/troops/edit.html.haml
= render 'errors'

.panel.panel-default
  .panel-heading Edytuj jednostkę
  .panel-body
    = render 'form'

Editor/app/views/troops/index.html.haml
.panel.panel-default
  .panel-heading Lista jednostek
  .panel-body
    .btn-group
      = link_to 'Dodaj', new_troop_path, class: 'btn btn-default'
      = link_to 'Pobierz JSON', troops_path( format: :json ), class: 'btn btn-default', target: '_blank'
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Town
          %th Type
          %th Cost
          %th Level
          %th Upgrade
          %th Abilities
          %th Max Health
          %th Max Damage
          %th Min Damage
          %th Range
          %th Akcja
      %tbody  
        - @troops.each_with_index do |troop, i|
          %tr{ id: dom_id( troop ) }
            %td= i + 1
            %td= troop.name
            %td= link_to troop.town.name, edit_town_path( troop.town )       if troop.town
            %td= link_to troop.type.name, edit_troop_type_path( troop.type ) if troop.type
            %td= troop.cost
            %td= troop.level
            %td= content_tag :span, '', class: ( troop.upgrade ? 'glyphicon glyphicon-ok-sign' : 'glyphicon glyphicon-minus-sign' )
            %td= troop.abilities
            %td= troop.max_health
            %td= troop.max_damage
            %td= troop.min_damage
            %td= troop.range
            %td
              .btn-group
                = link_to 'Edytuj', edit_troop_path( troop ), class: 'btn btn-default'
                = link_to 'Usuń', troop, class: 'btn btn-default', data: { confirm: 'Jesteś pewien?' }, method: :delete, remote: true
            

Editor/app/views/troops/new.html.haml
= render 'errors'

.panel.panel-default
  .panel-heading Dodaj jednostkę
  .panel-body
    = render 'form'