Editor/config/routes.rb
Heroes::Application.routes.draw do

  root 'pages#index'
  
  resources :fields
  resources :grounds
  resources :heroes
  resources :maps do
    get 'fields',    on: :member
    get 'randomize', on: :member
  end
  resources :mines
  resources :towns  
  resources :troops
  resources :troop_types
    
end

Editor/app/models/map.rb
class Map < ActiveRecord::Base
  before_save :set_objectives

  before_create :set_size
  before_create :set_max_player_count
  before_create :set_max_town_count
  after_create  :create_fields

  attr_accessor :is_random, :size, :victory_condition, :defeat_condition

  has_many :fields, dependent: :delete_all
  
  scope :by_name, -> { order( name: :asc ) }
  
  # validates :height, presence: true
  validates :name, presence: true
  validates :size, on: :create, presence: true
  # validates :town_count, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 8 }
  # validates :width,  presence: true

  def as_json options = {}
    {
      id:     id,
      name:   name,
      height: height,
      width:  width,
      victory: victory.to_s,
      defeat: defeat.to_s,
      max_player_count: max_player_count,
      town_count: town_count_json,
      towns:  towns_json,
      mines:  mines_json,
      fields: fields_json
    }
  end

  def randomize
    # randomize_fields
    randomize_towns
    randomize_mines
  end

  private

  def set_max_player_count
    self.max_player_count = size.to_i / 8
  end

  def set_max_town_count
    self.max_town_count = size.to_i / 4
  end  

  def fields_json
    json = []

    fields.includes( :ground ).all.each do |field|
      json << { x: field.x, y: field.y, texture_id: field.ground.sprite, cost: field.ground.cost, color: field.ground.color }
    end

    json
  end

  def mines_json
    json = []

    fields.where.not( mine_id: nil ).each do |field|
      if field.mine_id.to_i > 0
        json << { x: field.x, y: field.y, mine_id: field.mine_id }
      end
    end

    json
  end

  def towns_json
    json = []

    fields.where.not( town_id: nil ).each do |field|
      if field.town_id.to_i > 0
        json << { x: field.x, y: field.y, town_id: field.town_id }
      end
    end

    json
  end

  def town_count_json
    town_count = 0
    
    fields.where.not( town_id: nil ).each do |field|
      if field.town_id.to_i > 0
        town_count += 1
      end
    end

    town_count
  end

  def set_objectives
    self.victory = victory_condition unless victory_condition.blank?
    self.defeat  = defeat_condition  unless defeat_condition.blank?
  end

  def set_size
    self.height = self.width = size
  end

  def create_fields
    @fields = Hash.new

    ground = Ground.first

    (1..height).each_with_index do |y|
      (1..width).each_with_index do |x|
        @fields[[y, x]] = Field.create( x: x, y: y, ground_id: ground.id, map_id: id )
      end
    end
    
    randomize if is_random.to_i > 0
  end

  def randomize_fields
    fields.all.each do |f| 
      f.ground = Ground.random.first

      f.save 
    end
  end

  def randomize_towns 
    ( 1..max_town_count ).each do
      y = x = 0

      until can_build_town_at?( y, x )
        x = rand( 1..width )
        y = rand( 1..height )
      end

      build_town_at( y, x )
    end
  end

  def build_town_at( y, x )
    @fields[[y, x]].update( town: Town.random.first )
  end

  def can_build_town_at?( y, x )
    return false if y == 0 and x == 0

    permission = true
    
    radius = ( width / 5 ).to_i
    
    start_y = y - radius < 1 ? 1 : y - radius 
    end_y   = y + radius > width ? width : y + radius

    start_x = x - radius < 1 ? 1 : x - radius 
    end_x   = x + radius > width ? width : x + radius

    ( start_y .. end_y ).each do |y|
      ( start_x .. end_x ).each do |x|
        if @fields[[y, x]].town 
          permission = false

          break
        end
      end
    end

    permission
  end

  def randomize_mines
    radius = 2

    fields.where.not( town_id: nil ).each do |f|
      start_y = f.y - radius < 1 ? 1 : f.y - radius 
      end_y   = f.y + radius > width ? width : f.y + radius

      start_x = f.x - radius < 1 ? 1 : f.x - radius 
      end_x   = f.x + radius > width ? width : f.x + radius     

      Mine.all.each do |m|
        y = x = 0

        until can_build_mine_at?( y, x )
          x = rand( start_x..end_x )
          y = rand( start_y..end_y )
        end

        build_mine_at( m, y, x )
      end
    end
  end

  def can_build_mine_at?( y, x )
    return false if y == 0 and x == 0

    field = @fields[[y, x]]

    return if field.town or field.mine 

    return true
  end  

  def build_mine_at( mine, y, x )
    @fields[[y, x]].update( mine: mine )
  end  

end

Editor/app/controllers/maps_controller.rb
# encoding: utf-8

class MapsController < ApplicationController
  before_filter :get_map,    except: [:fields, :index, :new, :create]
  before_filter :get_fields, only:   [:fields]

  def index
    @maps = Map.by_name

    respond_to do |format|
      format.html 
      format.json { send_data @maps.to_json, type: :json, disposition: 'attachment' }
    end
  end

  def show
    respond_to do |format|
      format.json { send_data @map.to_json, type: :json, disposition: 'attachment' }
    end
  end

  def new
    @map = Map.new
  end

  def create
    @map = Map.new( map_params )
    
    if @map.save
      redirect_to maps_path, notice: 'Mapa została dodana'
    else
      render 'new'
    end    
  end

  def edit

  end

  def update
    @map.update( map_update_params )
    
    redirect_to maps_path, notice: 'Mapa została zaktualizowana'
  end

  def destroy
    @map.destroy

    respond_to do |format|
      format.js
    end
  end

  def fields
    @map = Map.find( params[:id] )

    @fields = @map.fields.includes( :ground ).order( 'y asc, x asc' )
  end

  def randomize
    @map.randomize

    redirect_to fields_map_path( @map )
  end

  private

  def get_map
    @map = Map.find( params[:id] )
  end

  def get_fields
    @grounds = Ground.by_name
    @mines   = Mine.by_name
    @towns   = Town.by_name
  end

  def map_params
    params.require( :map ).permit( [:is_random, :name, :victory_condition, :defeat_condition, :size, :town_count] )
  end 

  def map_update_params
    params.require( :map ).permit( [:name, :victory_condition, :defeat_condition] )
  end     
end

Editor/app/helpers/maps_helper.rb
module MapsHelper
end

Editor/app/views/maps/_errors.html.haml
- if @map.errors.any?
  .alert.alert-danger
    %ul
      - @map.errors.full_messages.each do |message|
        %li
          = message

Editor/app/views/maps/_form.html.haml
= form_for @map do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :victory_condition
    = f.select :victory_condition, [ [ 'Zdobycie wszystkich miast' ], [ 'Zdobycie wszystkich budynków' ], [ 'Zgromadzenie surowców' ], [ 'Pokonanie wszystkich jednostek przeciwnika' ] ], { prompt: 'Warunki zwycięstwa' }, class: 'form-control'  
  .form-group
    = f.label :defeat_condition
    = f.select :defeat_condition, [ [ 'Utrata wszystkich miast' ], [ 'Utrata wszystkich budynków' ], [ 'Utrata wszystkich jednostek' ], [ 'Utrata wszystkich miast i jednostek' ], [ 'Utrata wszystkich surowców' ] ], { prompt: 'Warunki porażki' }, class: 'form-control'

  - if f.object.new_record?
    .form-group
      = f.label :is_random
      = f.check_box :is_random, class: 'form-control' 
    / .form-group
    /   = f.label :town_count
    /   = f.number_field :town_count, class: 'form-control', value: 0
    .form-group
      = f.label :size
      = f.select :size, [ [ '16x16', 16 ], [ '32x32', 32 ], [ '48x48', 48 ] ], { prompt: 'Wybierz rozmiar' }, class: 'form-control'  
    /.form-group
    /  = f.label :height
    /  = f.number_field :height, class: 'form-control'
    /.form-group
    /  = f.label :width
    /  = f.number_field :width, class: 'form-control'        

  = f.submit 'Zapisz', class: 'btn btn-default'

Editor/app/views/maps/edit.html.haml
= render 'errors'

.panel.panel-default
  .panel-heading Edytuj mapę
  .panel-body
    = render 'form'

Editor/app/views/maps/fields.html.haml
.panel.panel-default
  .panel-heading 
    = "Edytuj pola mapy '#{ @map.name }' (#{ @map.width } x #{ @map.height })"
  .panel-body

    .row.selector
      .col-lg-3  
        %h3 Powierzchnie
        - @grounds.each_with_index do |ground, i|
          .radio
            %label
              = radio_button_tag( :ground_id, ground.id, ( i == 0 ? true : false ), data: { sprite: ground.sprite } )
              = ground.name

      .col-lg-3  
        %h3 Wybór powierzchni
        .radio
          %label
            = radio_button_tag( :mode_id, 1, true )
            Pojedyńczo
        .radio
          %label
            = radio_button_tag( :mode_id, 2, false )
            Zaznaczenie            

      .col-lg-3
        %h3 Miasta
        .radio
          %label
            = radio_button_tag( :town_id, 0, true, data: { sprite: -1 } )
            Brak
        - @towns.each do |town|
          .radio
            %label
              = radio_button_tag( :town_id, town.id, false, data: { sprite: town.sprite } )
              = town.name    

      .col-lg-3
        %h3 Kopalnie
        .radio
          %label
            = radio_button_tag( :mine_id, 0, true, data: { sprite: -1 } )
            Brak
        - @mines.each do |mine|
          .radio
            %label
              = radio_button_tag( :mine_id, mine.id, false, data: { sprite: mine.sprite } )
              = mine.name                     

    .fields{ data: { map_id: @map.id, path: fields_path, size: @map.width } }
      .inner
        - @fields.each_with_index do |field, i|
          .field{ data: { y: field.y, x: field.x } }
            - if field.town
              .field-sprite.building{ style: "background-position: -#{ field.town.sprite * 50 }px 0; z-index: #{ field.y + field.x };" }
            - elsif field.mine
              .field-sprite.building{ style: "background-position: -#{ field.mine.sprite * 50 }px 0; z-index: #{ field.y + field.x };" }
            - elsif field.ground
              .field-sprite.ground{ style: "background-position: -#{ field.ground.sprite * 50  }px 0; z-index: #{ field.y + field.x };" }
            - else
              .field-sprite.ground{ style: "z-index: #{ field.y + field.x };" }
          - if field.x == @map.width
            .clear
      .clear

Editor/app/views/maps/index.html.haml
.panel.panel-default
  .panel-heading Lista map
  .panel-body
    .btn-group
      = link_to 'Dodaj', new_map_path, class: 'btn btn-default'
      = link_to 'Pobierz JSON', maps_path( format: :json ), class: 'btn btn-default', target: '_blank'
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Size
          %th Victory
          %th Defeat
          %th Max Player Count
          %th Max Town Count
          %th Akcja
      %tbody  
        - @maps.each_with_index do |map, i|
          %tr{ id: dom_id( map ) }
            %td= i + 1
            %td= map.name
            %td= "#{ map.width } x #{ map.height }"
            %td= map.victory.to_s
            %td= map.defeat.to_s
            %td= map.max_player_count
            %td= map.max_town_count
            %td
              .btn-group
                = link_to 'Pobierz', map_path( map, format: :json ), class: 'btn btn-default', target: '_blank'
                = link_to 'Edytuj', edit_map_path( map ), class: 'btn btn-default'
                = link_to 'Edytuj pola', fields_map_path( map ), class: 'btn btn-default'
                / = link_to 'Losowa mapa', randomize_map_path( map ), class: 'btn btn-default', data: { confirm: 'Pola zostaną nadpisane. Jesteś pewien?' }
                = link_to 'Usuń', map, class: 'btn btn-default', data: { confirm: 'Jesteś pewien?' }, method: :delete, remote: true
            

Editor/app/views/maps/new.html.haml
= render 'errors'

.panel.panel-default
  .panel-heading Dodaj mapę
  .panel-body
    = render 'form'

Editor/app/views/maps/randomize.html.haml
= render file: 'maps/fields'