Editor/config/routes.rb
Heroes::Application.routes.draw do

  root 'pages#index'
  
  resources :fields
  resources :grounds
  resources :heroes
  resources :maps do
    get 'fields',    on: :member
    get 'randomize', on: :member
  end
  resources :mines
  resources :towns  
  resources :troops
  resources :troop_types
    
end

Editor/app/views/pages/index.html.haml
.panel.panel-default
  .panel-heading Edytor
  .panel-body
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Nazwa
          %th Akcja
      %tbody  
        %tr
          %td 1
          %td Mapy
          %td 
            .btn-group
              = link_to 'Lista', maps_path, class: 'btn btn-default'
              = link_to 'Pobierz JSON', maps_path( format: :json ), class: 'btn btn-default', target: '_blank'        
        %tr
          %td 2
          %td Powierzchnie
          %td 
            .btn-group
              = link_to 'Lista', grounds_path, class: 'btn btn-default'
              = link_to 'Pobierz JSON', grounds_path( format: :json ), class: 'btn btn-default', target: '_blank'
        %tr
          %td 3
          %td Kopalnie
          %td 
            .btn-group
              = link_to 'Lista', mines_path, class: 'btn btn-default'
              = link_to 'Pobierz JSON', mines_path( format: :json ), class: 'btn btn-default', target: '_blank'
        %tr
          %td 4
          %td Miasta
          %td 
            .btn-group
              = link_to 'Lista', towns_path, class: 'btn btn-default'
              = link_to 'Pobierz JSON', towns_path( format: :json ), class: 'btn btn-default', target: '_blank'
        %tr
          %td 5
          %td Bohaterowie
          %td 
            .btn-group
              = link_to 'Lista', heroes_path, class: 'btn btn-default'
              = link_to 'Pobierz JSON', heroes_path( format: :json ), class: 'btn btn-default', target: '_blank'
        %tr
          %td 6
          %td Jednostki
          %td 
            .btn-group
              = link_to 'Lista', troops_path, class: 'btn btn-default'
              = link_to 'Pobierz JSON', troops_path( format: :json ), class: 'btn btn-default', target: '_blank'                                                                    
        %tr
          %td 7
          %td Typy jednostek
          %td 
            .btn-group
              = link_to 'Lista', troop_types_path, class: 'btn btn-default'
              = link_to 'Pobierz JSON', troop_types_path( format: :json ), class: 'btn btn-default', target: '_blank'