Editor/config/routes.rb
Heroes::Application.routes.draw do

  root 'pages#index'
  
  resources :fields
  resources :grounds
  resources :heroes
  resources :maps do
    get 'fields',    on: :member
    get 'randomize', on: :member
  end
  resources :mines
  resources :towns  
  resources :troops
  resources :troop_types
    
end

Editor/app/models/town.rb
class Town < ActiveRecord::Base
  belongs_to :ground

  has_many :heroes
  has_many :troops

  scope :by_name, -> { order( name: :asc ) }
  scope :random,  -> { order( 'random()' ) }
  
  validates :ground, presence: true
  validates :name,   presence: true

  def as_json options = {}
    {
      id:         id,
      texture_id: ground_id,
      name:       name,
      heroes:     heroes,
      sprite:     sprite.to_s,
      troops:     troops
    }
  end  
end

Editor/app/controllers/towns_controller.rb
# encoding: utf-8

class TownsController < ApplicationController
  before_filter :get_town, except: [:index, :new, :create]

  def index
    @towns = Town.includes( [:heroes, :troops] ).by_name

    respond_to do |format|
      format.html 
      format.json { send_data @towns.to_json, type: :json, disposition: 'attachment' }
    end
  end

  def new
    @town = Town.new
  end

  def create
    @town = Town.new( town_params )
    
    if @town.save
      redirect_to towns_path, notice: 'Miasto zostało dodane'
    else
      render 'new'
    end    
  end

  def edit

  end

  def update
    @town.update( town_params )
    
    redirect_to towns_path, notice: 'Miasto zostało zaktualizowane'
  end

  def destroy
    @town.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def get_town
    @town = Town.find( params[:id] )
  end

  def town_params
    params.require( :town ).permit( [:ground_id, :name, :sprite] )
  end  
end

Editor/app/helpers/towns_helper.rb
module TownsHelper
end

Editor/app/views/towns/_errors.html.haml
- if @town.errors.any?
  .alert.alert-danger
    %ul
      - @town.errors.full_messages.each do |message|
        %li
          = message

Editor/app/views/towns/_form.html.haml
= form_for @town do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label  :ground_id
    = f.select :ground_id, Ground.by_name.collect{ |g| [g.name, g.id] }, { prompt: 'Wybierz powierzchnię' }, class: 'form-control'  
  .form-group
    = f.label :sprite
    = f.hidden_field :sprite
    .sprite
      = image_tag 'buildings.png', height: 100, width: 400

  = f.submit 'Zapisz', class: 'btn btn-default'

Editor/app/views/towns/edit.html.haml
= render 'errors'

.panel.panel-default
  .panel-heading Edytuj miasto
  .panel-body
    = render 'form'

Editor/app/views/towns/index.html.haml
.panel.panel-default
  .panel-heading Lista miast
  .panel-body
    .btn-group
      = link_to 'Dodaj', new_town_path, class: 'btn btn-default'
      = link_to 'Pobierz JSON', towns_path( format: :json ), class: 'btn btn-default', target: '_blank'
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Ground
          %th Sprite
          %th Heroes
          %th Troops
          %th Akcja
      %tbody  
        - @towns.each_with_index do |town, i|
          %tr{ id: dom_id( town ) }
            %td= i + 1
            %td= town.name
            %td= link_to town.ground.name, edit_ground_path( town.ground ) if town.ground
            %td
              .display-sprite
                = image_tag 'buildings.png', height: 100, style: "margin-left: -#{ town.sprite * 50 }px;"            
            %td= raw town.heroes.by_name.collect{ |h| link_to h.name, edit_hero_path( h ) }.to_sentence
            %td= raw town.troops.by_name.collect{ |t| link_to t.name, edit_troop_path( t ) }.to_sentence
            %td
              .btn-group
                = link_to 'Edytuj', edit_town_path( town ), class: 'btn btn-default'
                = link_to 'Usuń', town, class: 'btn btn-default', data: { confirm: 'Jesteś pewien?' }, method: :delete, remote: true
            

Editor/app/views/towns/new.html.haml
= render 'errors'

.panel.panel-default
  .panel-heading Dodaj miasto
  .panel-body
    = render 'form'